### ISSUE TITLE
Crash when attempting to select template in dropdown

### ISSUE THREAD

**Issue by neilenns** [vatis-project/vatis#132]
Beta 11

To reproduce:

1. Run vatis, select one of your profiles
2. Click the dropdown at the bottom of the main window to try and select a template

Result:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Win32.SystemEvents, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'Microsoft.Win32.SystemEvents, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at System.Drawing.Internal.SystemColorTracker.Add(ISystemColorTracker obj)
   at System.Drawing.SolidBrush..ctor(Color color)
   at System.Drawing.SystemBrushes.FromSystemColor(Color c)
   at System.Windows.Forms.GdiPlusCache.GetSolidBrushScope(Color color)
   at System.Windows.Forms.GdiPlusCache.GetCachedSolidBrushScope(Color color)
   at System.Windows.Forms.DrawItemEventArgs.DrawBackground()
   at Vatsim.Vatis.UI.Controls.ExComboBox.OnDrawItem(DrawItemEventArgs e) in Vatsim.Vatis\UI\Controls\ExComboBox.cs:line 52
   at System.Windows.Forms.ComboBox.WmReflectDrawItem(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by neilenns** [comment]
I'm getting this all over the place. If I try and click the `Manage Profile` button it happens too.

This version was auto-installed via the update check. I'll try uninstalling and installing from the releases page and see if that fixes it.

**Comment by neilenns** [comment]
Installing from the releases page made the crash go away.

**Comment by justinshannon** [comment]
This is an issue with the silent updater installer. Going forward, the silent updater will no longer be packaged as `self-contained` and instead include all the required .NET dependencies which should prevent these errors in the future.
