### ISSUE TITLE
Unhandled exception following navdata update

### ISSUE THREAD

**Issue by luke11brown** [vatis-project/vatis#197]
vATIS downloads latest navdata on start, gets stuck on "loading navdata" screen with unhandled exception.

```
************** Exception Text **************
Newtonsoft.Json.JsonReaderException: Could not convert string to double: ﻿22.328610. Path '[12072].Lat', line 1, position 912416.
   at Newtonsoft.Json.JsonReader.ReadDoubleString(String s)
   at Newtonsoft.Json.JsonTextReader.FinishReadQuotedNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsDouble()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Vatsim.Vatis.NavData.NavDataRepository.<>c.<LoadAirportDatabase>b__5_0() in Vatsim.Vatis\NavData\NavDataRepository.cs:line 36
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Vatsim.Vatis.NavData.NavDataRepository.LoadAirportDatabase() in Vatsim.Vatis\NavData\NavDataRepository.cs:line 32
   at Vatsim.Vatis.NavData.NavDataRepository.Initialize() in Vatsim.Vatis\NavData\NavDataRepository.cs:line 17
   at Vatsim.Vatis.UI.Startup.StartupWindow.OnShown(EventArgs e) in Vatsim.Vatis\UI\Startup\StartupWindow.cs:line 66
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Private.CoreLib.dll
----------------------------------------
vATIS
    Assembly Version: 4.0.0.15
    Win32 Version: 4.0.0.15
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/vATIS.dll
----------------------------------------
System.Runtime
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Runtime.dll
----------------------------------------
Ninject
    Assembly Version: 3.3.6.0
    Win32 Version: 3.3.6.0
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/Ninject.dll
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/netstandard.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2523.51916
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Windows.Forms.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2523.51916
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Windows.Forms.Primitives.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.ComponentModel.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.3.27908
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/Newtonsoft.Json.dll
----------------------------------------
System.Threading
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Threading.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Threading.Thread.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Drawing.Common.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Collections.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.ComponentModel.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Collections.Concurrent.dll
----------------------------------------
Serilog.Sinks.File
    Assembly Version: 5.0.1.0
    Win32 Version: 5.0.1.0
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/Serilog.Sinks.File.dll
----------------------------------------
Serilog
    Assembly Version: 2.0.0.0
    Win32 Version: 3.0.0.0
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/Serilog.dll
----------------------------------------
System.Linq
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Linq.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Text.Encoding.Extensions.dll
----------------------------------------
System.IO.FileSystem
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.IO.FileSystem.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Private.Uri.dll
----------------------------------------
System.Linq.Expressions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Linq.Expressions.dll
----------------------------------------
Ninject.Extensions.Factory
    Assembly Version: 3.3.3.0
    Win32 Version: 3.3.3.0
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/Ninject.Extensions.Factory.dll
----------------------------------------
Castle.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.2.0
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/Castle.Core.dll
----------------------------------------
Vatsim.Network
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/Vatsim.Network.dll
----------------------------------------
System.Reflection
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Reflection.dll
----------------------------------------
System.Reflection.TypeExtensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Reflection.TypeExtensions.dll
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Reflection.Primitives.dll
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Runtime.Extensions.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Collections.Specialized.dll
----------------------------------------
System.Reflection.Emit
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Reflection.Emit.dll
----------------------------------------
DynamicProxyGenAssembly2
    Assembly Version: 0.0.0.0
    Win32 Version: 4.2.0
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/Castle.Core.dll
----------------------------------------
DynamicProxyGenAssembly2
    Assembly Version: 0.0.0.0
    Win32 Version: 4.2.0
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/Castle.Core.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Memory
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Memory.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.ObjectModel.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.2523.51916
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/Accessibility.dll
----------------------------------------
CredentialManagement
    Assembly Version: 1.0.4.0
    Win32 Version: 1.0.4.0
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/CredentialManagement.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Runtime.Numerics
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Runtime.Numerics.dll
----------------------------------------
System.Runtime.Serialization.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Runtime.Serialization.Primitives.dll
----------------------------------------
System.Data.Common
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Data.Common.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Private.Xml.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Private.CoreLib.dll
----------------------------------------
System.Drawing
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2523.51916
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Drawing.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/Microsoft.Win32.Primitives.dll
----------------------------------------
System.Security.Permissions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Security.Permissions.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Numerics.Vectors.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Resources.Extensions.dll
----------------------------------------
System.Net.Http
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Net.Http.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Net.Primitives.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Diagnostics.Tracing.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Collections.NonGeneric.dll
----------------------------------------
System.Net.Security
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Net.Security.dll
----------------------------------------
System.Security.Cryptography.X509Certificates
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Security.Cryptography.X509Certificates.dll
----------------------------------------
System.Net.Sockets
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Net.Sockets.dll
----------------------------------------
System.Net.NameResolution
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Net.NameResolution.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Threading.ThreadPool.dll
----------------------------------------
System.Threading.Overlapped
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Threading.Overlapped.dll
----------------------------------------
System.Security.Cryptography.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Security.Cryptography.Primitives.dll
----------------------------------------
System.Security.Principal.Windows
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Security.Principal.Windows.dll
----------------------------------------
System.Security.Claims
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Security.Claims.dll
----------------------------------------
System.Security.Cryptography.Encoding
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Security.Cryptography.Encoding.dll
----------------------------------------
System.Net.Http.Json
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Net.Http.Json.dll
----------------------------------------
System.Text.Json
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Text.Json.dll
----------------------------------------
System.Text.Encodings.Web
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Text.Encodings.Web.dll
----------------------------------------
System.Runtime.Intrinsics
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Runtime.Intrinsics.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Runtime.Loader.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.Collections.Immutable.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2523.51912
    CodeBase: file:///C:/Users/luke1/AppData/Local/vATIS-4.0/Application/System.IO.Compression.dll
----------------------------------------

************** JIT Debugging **************
```

**Comment by maxlk96** [comment]
Several users in Sweden have the same issue

**Comment by Goritoo11** [comment]
Romania here and same issue

**Comment by neilenns** [comment]
The issue is a single bad piece of airport data. To work around the issue:

1. Open `%localappdata%/vATIS-4.0/Airports.json` in a text editor
2. Search for `22.328610`. You'll see there's a garbage character in front of the 2.
3. Delete the garbage character
4. Save the file

vATIS will run properly.

**Comment by neilenns** [comment]
On the coding side, to fix this the JSON parsing should include an error handler that logs the error then continues processing the JSON document. I'd open a PR for it but I'm having trouble building locally. Here is an example of the change needed at https://github.com/vatis-project/vatis/blob/a874ba98b0c35e4c40a5e7c57a362b16ad04574e/Vatsim.Vatis/NavData/NavDataRepository.cs#L36:


```C#
            return JsonConvert.DeserializeObject<List<Airport>>(reader.ReadToEnd(), new JsonSerializerSettings()
            {
                // Add an explicit error handler so individual bad records get skipped instead of
                // having the entire load fail just because of one bad record.
                Error = (sender, args) =>
                {
                    Log.Error($"Unable to parse airport: {args.ErrorContext.Error.Message}");
                    args.ErrorContext.Handled = true;
                }
            });
```

A similar change should be applied to `LoadNavaidDatabase()` as well.
