### ISSUE TITLE
vATIS Unhandled Exception on Connect

### ISSUE THREAD

**Issue by scotflieger** [vatis-project/vatis#94]
Using 4.0.0 beta 3 I am getting an unhandled exception error and crash when I attempt to Connect. Previously vATIS has been working reliably. The error first appeared after the VATSIM servers recently changed from UK to AUTOMATIC.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vatsim.Vatis.Client.Network.Connection.Connect() in Vatsim.Vatis.Client\Network\Connection.cs:line 263
   at Vatsim.Vatis.Client.MainForm.<>c__DisplayClass43_0.<RefreshAtisComposites>b__2(Object sender, EventArgs args) in Vatsim.Vatis.Client\MainForm.cs:line 339
   at Vatsim.Vatis.Client.UI.CompositePanel.btnTransmit_Click(Object sender, EventArgs e) in Vatsim.Vatis.Client\UI\CompositePanel.cs:line 250
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at Vatsim.Vatis.Client.UI.ExButton.OnMouseUp(MouseEventArgs e) in Vatsim.Vatis.Client\UI\ExButton.cs:line 80
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by scotflieger** [comment]
The exception is caused by having no server selected in Settings. This is as a result of changes in the available servers.
